GET http://localhost:3000/login


###



POST http://localhost:3000/register
Content-Type: application/json

{
    "name": "Dawid",
    "password": "password",
    "email":"dawid@gmail.com"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "Dawid", "password": "password"
}

